server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie

#MyBatis
spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//15.164.222.200:1521/XE
      username: hr
      password: hr
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: cyberkdy2@gmail.com # 3
    password: qnyfmgktsqedxnea # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c4b51a9523682afb89b2d9dca35e3d2e
            redirect-uri: http://localhost:10000/kakao/login
            authorization-grant-type: authorization_code
            client-authentication-method: GET
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#multipart
servlet:
  multipart:
    enabled: true
    max-request-size: 40MB
    max-file-size: 40MB
    file-size-threshold: 100MB




